name: GitHub Metrics

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Generate simplified GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: ahmedjk34
          template: classic
          base: ""
          config_timezone: Asia/Hebron

          plugin_skyline: yes
          plugin_skyline_year: current
          plugin_skyline_frames: 1

          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_limit: 8
